//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemini.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gemini.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to set value: {0} 的本地化字符串。
        /// </summary>
        public static string AdvancedSliderCommitErrorFormat {
            get {
                return ResourceManager.GetString("AdvancedSliderCommitErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Files 的本地化字符串。
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Supported Files 的本地化字符串。
        /// </summary>
        public static string AllSupportedFiles {
            get {
                return ResourceManager.GetString("AllSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Edit 的本地化字符串。
        /// </summary>
        public static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Redo 的本地化字符串。
        /// </summary>
        public static string EditRedoCommandText {
            get {
                return ResourceManager.GetString("EditRedoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string EditRedoCommandToolTip {
            get {
                return ResourceManager.GetString("EditRedoCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Undo 的本地化字符串。
        /// </summary>
        public static string EditUndoCommandText {
            get {
                return ResourceManager.GetString("EditUndoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string EditUndoCommandToolTip {
            get {
                return ResourceManager.GetString("EditUndoCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Close 的本地化字符串。
        /// </summary>
        public static string FileCloseCommandText {
            get {
                return ResourceManager.GetString("FileCloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string FileCloseCommandToolTip {
            get {
                return ResourceManager.GetString("FileCloseCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E_xit 的本地化字符串。
        /// </summary>
        public static string FileExitCommandText {
            get {
                return ResourceManager.GetString("FileExitCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string FileExitCommandToolTip {
            get {
                return ResourceManager.GetString("FileExitCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _New 的本地化字符串。
        /// </summary>
        public static string FileNewCommandText {
            get {
                return ResourceManager.GetString("FileNewCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string FileNewCommandToolTip {
            get {
                return ResourceManager.GetString("FileNewCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untitled {0} 的本地化字符串。
        /// </summary>
        public static string FileNewUntitled {
            get {
                return ResourceManager.GetString("FileNewUntitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open 的本地化字符串。
        /// </summary>
        public static string FileOpenCommandText {
            get {
                return ResourceManager.GetString("FileOpenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string FileOpenCommandToolTip {
            get {
                return ResourceManager.GetString("FileOpenCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Files 的本地化字符串。
        /// </summary>
        public static string FileRecentFilesCommandText {
            get {
                return ResourceManager.GetString("FileRecentFilesCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Files 的本地化字符串。
        /// </summary>
        public static string FileRecentFilesCommandToolTip {
            get {
                return ResourceManager.GetString("FileRecentFilesCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save All 的本地化字符串。
        /// </summary>
        public static string FileSaveAllCommandText {
            get {
                return ResourceManager.GetString("FileSaveAllCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save All 的本地化字符串。
        /// </summary>
        public static string FileSaveAllCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveAllCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save _As... 的本地化字符串。
        /// </summary>
        public static string FileSaveAsCommandText {
            get {
                return ResourceManager.GetString("FileSaveAsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As 的本地化字符串。
        /// </summary>
        public static string FileSaveAsCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveAsCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save 的本地化字符串。
        /// </summary>
        public static string FileSaveCommandText {
            get {
                return ResourceManager.GetString("FileSaveCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string FileSaveCommandToolTip {
            get {
                return ResourceManager.GetString("FileSaveCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Help 的本地化字符串。
        /// </summary>
        public static string HelpMenuText {
            get {
                return ResourceManager.GetString("HelpMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        public static string HistoryDisplayName {
            get {
                return ResourceManager.GetString("HistoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial State 的本地化字符串。
        /// </summary>
        public static string HistoryInitialState {
            get {
                return ResourceManager.GetString("HistoryInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string LanguageSystem {
            get {
                return ResourceManager.GetString("LanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto hide main menu 的本地化字符串。
        /// </summary>
        public static string MainMenuSettingsAutoHideMainMenu {
            get {
                return ResourceManager.GetString("MainMenuSettingsAutoHideMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Theme: 的本地化字符串。
        /// </summary>
        public static string MainMenuSettingsColorTheme {
            get {
                return ResourceManager.GetString("MainMenuSettingsColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language: 的本地化字符串。
        /// </summary>
        public static string MainMenuSettingsLanguage {
            get {
                return ResourceManager.GetString("MainMenuSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requires restart 的本地化字符串。
        /// </summary>
        public static string MainMenuSettingsLanguageRestart {
            get {
                return ResourceManager.GetString("MainMenuSettingsLanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Default Title] 的本地化字符串。
        /// </summary>
        public static string MainWindowDefaultTitle {
            get {
                return ResourceManager.GetString("MainWindowDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save changes to the {0} &quot;{1}&quot; before closing? 的本地化字符串。
        /// </summary>
        public static string SaveChangesBeforeClosingMessage {
            get {
                return ResourceManager.GetString("SaveChangesBeforeClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string SettingsDisplayName {
            get {
                return ResourceManager.GetString("SettingsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string SettingsPageGeneral {
            get {
                return ResourceManager.GetString("SettingsPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environment 的本地化字符串。
        /// </summary>
        public static string SettingsPathEnvironment {
            get {
                return ResourceManager.GetString("SettingsPathEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue 的本地化字符串。
        /// </summary>
        public static string ThemeBlueName {
            get {
                return ResourceManager.GetString("ThemeBlueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string ThemeDarkName {
            get {
                return ResourceManager.GetString("ThemeDarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string ThemeLightName {
            get {
                return ResourceManager.GetString("ThemeLightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard 的本地化字符串。
        /// </summary>
        public static string ToolBarStandard {
            get {
                return ResourceManager.GetString("ToolBarStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Category 的本地化字符串。
        /// </summary>
        public static string ToolboxCategory {
            get {
                return ResourceManager.GetString("ToolboxCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolbox 的本地化字符串。
        /// </summary>
        public static string ToolboxDisplayName {
            get {
                return ResourceManager.GetString("ToolboxDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Tools 的本地化字符串。
        /// </summary>
        public static string ToolsMenuText {
            get {
                return ResourceManager.GetString("ToolsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Options 的本地化字符串。
        /// </summary>
        public static string ToolsOptionsCommandText {
            get {
                return ResourceManager.GetString("ToolsOptionsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string ToolsOptionsCommandToolTip {
            get {
                return ResourceManager.GetString("ToolsOptionsCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Screen 的本地化字符串。
        /// </summary>
        public static string ViewFullScreenCommandText {
            get {
                return ResourceManager.GetString("ViewFullScreenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Screen 的本地化字符串。
        /// </summary>
        public static string ViewFullScreenCommandToolTip {
            get {
                return ResourceManager.GetString("ViewFullScreenCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _History 的本地化字符串。
        /// </summary>
        public static string ViewHistoryCommandText {
            get {
                return ResourceManager.GetString("ViewHistoryCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        public static string ViewHistoryCommandToolTip {
            get {
                return ResourceManager.GetString("ViewHistoryCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _View 的本地化字符串。
        /// </summary>
        public static string ViewMenuText {
            get {
                return ResourceManager.GetString("ViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolbo_x 的本地化字符串。
        /// </summary>
        public static string ViewToolboxCommandText {
            get {
                return ResourceManager.GetString("ViewToolboxCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolbox 的本地化字符串。
        /// </summary>
        public static string ViewToolboxCommandToolTip {
            get {
                return ResourceManager.GetString("ViewToolboxCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Window 的本地化字符串。
        /// </summary>
        public static string WindowMenuText {
            get {
                return ResourceManager.GetString("WindowMenuText", resourceCulture);
            }
        }
    }
}
