//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorDetection.Daq.NI_DAQ.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MotorDetection.Daq.NI_DAQ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Absolute value 的本地化字符串。
        /// </summary>
        internal static string Absolute_value {
            get {
                return ResourceManager.GetString("Absolute_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acceleration 的本地化字符串。
        /// </summary>
        internal static string Acceleration {
            get {
                return ResourceManager.GetString("Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amplitude (V) 的本地化字符串。
        /// </summary>
        internal static string Amplitude__V_ {
            get {
                return ResourceManager.GetString("Amplitude__V_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average number of triggers 的本地化字符串。
        /// </summary>
        internal static string Average_number_of_triggers {
            get {
                return ResourceManager.GetString("Average_number_of_triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calibration value 的本地化字符串。
        /// </summary>
        internal static string Calibration_value {
            get {
                return ResourceManager.GetString("Calibration_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel name 的本地化字符串。
        /// </summary>
        internal static string Channel_name {
            get {
                return ResourceManager.GetString("Channel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel type 的本地化字符串。
        /// </summary>
        internal static string Channel_type {
            get {
                return ResourceManager.GetString("Channel_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coupling mode 的本地化字符串。
        /// </summary>
        internal static string Coupling_mode {
            get {
                return ResourceManager.GetString("Coupling_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device model 的本地化字符串。
        /// </summary>
        internal static string Device_model {
            get {
                return ResourceManager.GetString("Device_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device name 的本地化字符串。
        /// </summary>
        internal static string Device_name {
            get {
                return ResourceManager.GetString("Device_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Select 的本地化字符串。
        /// </summary>
        internal static string Device_Select {
            get {
                return ResourceManager.GetString("Device_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displacement 的本地化字符串。
        /// </summary>
        internal static string Displacement {
            get {
                return ResourceManager.GetString("Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable trigger 的本地化字符串。
        /// </summary>
        internal static string Enable_trigger {
            get {
                return ResourceManager.GetString("Enable_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End frequency (Hz) 的本地化字符串。
        /// </summary>
        internal static string End_frequency__Hz_ {
            get {
                return ResourceManager.GetString("End_frequency__Hz_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engineering unit 的本地化字符串。
        /// </summary>
        internal static string Engineering_unit {
            get {
                return ResourceManager.GetString("Engineering_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Falling edge 的本地化字符串。
        /// </summary>
        internal static string Falling_edge {
            get {
                return ResourceManager.GetString("Falling_edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequency / start frequency (Hz) 的本地化字符串。
        /// </summary>
        internal static string Frequency___start_frequency__Hz_ {
            get {
                return ResourceManager.GetString("Frequency___start_frequency__Hz_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IEPE 的本地化字符串。
        /// </summary>
        internal static string IEPE {
            get {
                return ResourceManager.GetString("IEPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input channel settings 的本地化字符串。
        /// </summary>
        internal static string Input_channel_settings {
            get {
                return ResourceManager.GetString("Input_channel_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input voltage  的本地化字符串。
        /// </summary>
        internal static string Input_voltage_ {
            get {
                return ResourceManager.GetString("Input_voltage_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lag length (usually used for hammer method) 的本地化字符串。
        /// </summary>
        internal static string Lag_length__usually_used_for_hammer_method_ {
            get {
                return ResourceManager.GetString("Lag_length__usually_used_for_hammer_method_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measure 的本地化字符串。
        /// </summary>
        internal static string Measure {
            get {
                return ResourceManager.GetString("Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Measurement type 的本地化字符串。
        /// </summary>
        internal static string Measurement_type {
            get {
                return ResourceManager.GetString("Measurement_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output channel settings 的本地化字符串。
        /// </summary>
        internal static string Output_channel_settings {
            get {
                return ResourceManager.GetString("Output_channel_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output voltage  的本地化字符串。
        /// </summary>
        internal static string Output_voltage_ {
            get {
                return ResourceManager.GetString("Output_voltage_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phase 的本地化字符串。
        /// </summary>
        internal static string Phase {
            get {
                return ResourceManager.GetString("Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference 的本地化字符串。
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh device list 的本地化字符串。
        /// </summary>
        internal static string Refresh_device_list {
            get {
                return ResourceManager.GetString("Refresh_device_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rising edge 的本地化字符串。
        /// </summary>
        internal static string Rising_edge {
            get {
                return ResourceManager.GetString("Rising_edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select trigger channel 的本地化字符串。
        /// </summary>
        internal static string Select_trigger_channel {
            get {
                return ResourceManager.GetString("Select_trigger_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acquisition 的本地化字符串。
        /// </summary>
        internal static string SettingsAcquisitionPageName {
            get {
                return ResourceManager.GetString("SettingsAcquisitionPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel 的本地化字符串。
        /// </summary>
        internal static string SettingsChannelPageGeneral {
            get {
                return ResourceManager.GetString("SettingsChannelPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger 的本地化字符串。
        /// </summary>
        internal static string SettingTriggerPageGeneral {
            get {
                return ResourceManager.GetString("SettingTriggerPageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time (s) 的本地化字符串。
        /// </summary>
        internal static string Time__s_ {
            get {
                return ResourceManager.GetString("Time__s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger amount 的本地化字符串。
        /// </summary>
        internal static string Trigger_amount {
            get {
                return ResourceManager.GetString("Trigger_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger mode 的本地化字符串。
        /// </summary>
        internal static string Trigger_mode_ {
            get {
                return ResourceManager.GetString("Trigger_mode_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Velocity 的本地化字符串。
        /// </summary>
        internal static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Voltage 的本地化字符串。
        /// </summary>
        internal static string Voltage {
            get {
                return ResourceManager.GetString("Voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waveform type 的本地化字符串。
        /// </summary>
        internal static string Waveform_type {
            get {
                return ResourceManager.GetString("Waveform_type", resourceCulture);
            }
        }
    }
}
